version: '3'
services:
#  myspringapp:
#    image: customer
#    build: .
#    ports:
#      - "8080:8080"
#    restart: always
#    depends_on:
#      - mypostgres
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres:5432/mydb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  postgres:
    container_name: mypostgres
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customer
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      #- ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8090:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin: